[package]
name = "aoc2023-day-07"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true, features = ["derive"] }
itertools = { workspace = true }
lazy_static = "1.4.0"
